import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg: {
          primary: 'var(--bg-primary)',
          secondary: 'var(--bg-secondary)',
          tertiary: 'var(--bg-tertiary)',
          hover: 'var(--bg-hover)',
          active: 'var(--bg-active)',
          input: 'var(--bg-input)',
          glass: 'var(--bg-glass)',
          'glass-light': 'var(--bg-glass-light)',
          'glass-heavy': 'var(--bg-glass-heavy)',
          base: 'var(--bg-base)',
        },
        border: {
          primary: 'var(--border-primary)',
          secondary: 'var(--border-secondary)',
          accent: 'var(--border-accent)',
          glass: 'var(--border-glass)',
          'glass-bright': 'var(--border-glass-bright)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          inverse: 'var(--text-inverse)',
        },
        buy: {
          DEFAULT: '#2962FF',
          light: '#448AFF',
          dark: '#1A3FA0',
          bg: 'rgba(41,98,255,0.07)',
          glow: 'rgba(41,98,255,0.2)',
        },
        sell: {
          DEFAULT: '#FF2440',
          light: '#FF5252',
          dark: '#B71C1C',
          bg: 'rgba(255,36,64,0.07)',
          glow: 'rgba(255,36,64,0.2)',
        },
        accent: { DEFAULT: '#F7931A', light: '#FFB74D', dark: '#E65100' },
        success: '#00C853',
        warning: '#FFB300',
        info: '#29B6F6',
        danger: '#FF1744',
        rainbow: {
          red: '#FF6B6B',
          orange: '#FFA94D',
          yellow: '#FFD43B',
          green: '#69DB7C',
          blue: '#4DABF7',
          purple: '#9775FA',
          pink: '#F06595',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        'xxs': ['10px', { lineHeight: '14px' }],
        'xs': ['11px', { lineHeight: '16px' }],
        'sm': ['12px', { lineHeight: '16px' }],
        'base': ['13px', { lineHeight: '20px' }],
        'md': ['14px', { lineHeight: '20px' }],
        'lg': ['16px', { lineHeight: '24px' }],
        'xl': ['20px', { lineHeight: '28px' }],
        '2xl': ['28px', { lineHeight: '36px' }],
        '3xl': ['36px', { lineHeight: '44px' }],
      },
      borderRadius: { sm: '4px', DEFAULT: '4px', md: '6px', lg: '8px', xl: '12px', '2xl': '16px', '3xl': '24px' },
      spacing: { '0.5': '2px', '1': '4px', '1.5': '6px', '2': '8px', '3': '12px', '4': '16px', '5': '20px', '6': '24px', '8': '32px', '10': '40px', '12': '48px' },
      backdropBlur: { xs: '2px', glass: '16px', 'glass-heavy': '24px', 'glass-ultra': '40px' },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-down': 'slideDown 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
        'flash-blue': 'flashBlue 0.15s ease-out',
        'flash-red': 'flashRed 0.15s ease-out',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { '0%': { opacity: '0', transform: 'translateY(-8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        flashBlue: { '0%': { backgroundColor: 'rgba(41,98,255,0.2)' }, '100%': { backgroundColor: 'transparent' } },
        flashRed: { '0%': { backgroundColor: 'rgba(255,36,64,0.2)' }, '100%': { backgroundColor: 'transparent' } },
        glowPulse: { '0%, 100%': { boxShadow: '0 0 20px rgba(41,98,255,0.15)' }, '50%': { boxShadow: '0 0 40px rgba(41,98,255,0.3)' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
      boxShadow: {
        'modal': '0 8px 32px rgba(0,0,0,0.6)',
        'dropdown': '0 4px 16px rgba(0,0,0,0.4)',
        'glass': '0 8px 32px 0 rgba(0,0,0,0.37)',
        'glass-sm': '0 4px 16px 0 rgba(0,0,0,0.25)',
        'glass-lg': '0 16px 48px 0 rgba(0,0,0,0.5)',
        'inner-light': 'inset 0 1px 0 0 rgba(255,255,255,0.05)',
        'skeu': 'inset 0 1px 0 rgba(255,255,255,0.08), inset 0 -1px 0 rgba(0,0,0,0.2), 0 2px 8px rgba(0,0,0,0.3)',
        'glow-blue': '0 0 20px rgba(41,98,255,0.3), 0 0 60px rgba(41,98,255,0.1)',
        'glow-red': '0 0 20px rgba(255,36,64,0.3), 0 0 60px rgba(255,36,64,0.1)',
      },
    },
  },
  plugins: [],
}

export default config
